Linked Images endpoint to the Model
ias-tcd/competitor-matching-model pull request #90
Opened 2024-02-29 15:12 UTC by dhrvrc

2024-02-29 20:09 UTC, sktylr requested changes
Nice work! It is working well locally and great to get this done in this sprint

2024-02-29 20:09 UTC, sktylr commented on api/images/services/LogoDetectionService.py
> +from ml.models.logo_detection.process import process as detectLogos
`snake_case`
```suggestion
from ml.models.logo_detection.process import process as detect_logos
```

2024-02-29 20:09 UTC, sktylr commented on api/images/services/LogoDetectionService.py
> +    def detect_in_image(self, imagePath):
`snake_case`
```suggestion
    def detect_in_image(self, image_path):
```

2024-02-29 20:09 UTC, sktylr commented on api/images/views.py
> +        print(request.data)
rm

2024-02-29 20:09 UTC, sktylr commented on api/images/services/ImageProcessingService.py
Let's change this file name to `image_processing_service.py` to conform to `snake_case` conventions. You can use `git mv` to rename whilst preserving the git history

2024-02-29 20:09 UTC, sktylr commented on api/images/services/LogoDetectionService.py
Likewise let's change to `logo_detection_service.py`

2024-03-01 10:07 UTC, sktylr commented on api/images/services/logo_detection_service.py
> +class logo_detection_service:
Sorry probably wasn't clear enough lol, class names should be `UpperCamelCase` and then file names, variable names and method / function names should be `snake_case`
```suggestion
class LogoDetectionService:
```

2024-03-01 10:07 UTC, sktylr commented on api/images/services/image_processing_service.py
> +class image_processing_service:
```suggestion
class ImageProcessingService:
```

2024-03-01 14:27 UTC, egaynor approved these changes

2024-03-01 15:31 UTC, sktylr approved these changes
🏆

2024-03-01 16:15 UTC, merged